language: python

python:
  - 2.7
  - 3.4

before_install:
  # Use conda to get recent numpy, cython, scipy
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a

install:
  - CONDAPKGS=(pip numpy scipy cython)
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION ${CONDAPKGS[*]}
  - source activate test-environment
  - ./.travis_no_output pip install https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.3.1/matplotlib-1.3.1.tar.gz
  # http://www.webupd8.org/2010/10/fix-nopubkey-error-for-extras-ubuntu.html
  - ./.travis_no_output sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - yes | ./.travis_no_output sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - ./.travis_no_output sudo apt-get update
  - ./.travis_no_output sudo apt-get install libgeos-dev libproj-dev
  - ./.travis_no_output pip install --use-mirrors shapely nose pyshp mock
  - ./.travis_no_output pip install pep8==1.4.5 owslib six
  - ./.travis_no_output pip install --use-mirrors pillow
  # install cartopy in the .local directory (in lieu of using virtual env...)
  - ./.travis_no_output python setup.py install

script:
  - mkdir ../test_folder
  - cd ../test_folder
  - nosetests cartopy --with-doctest -sv

after_failure:
  - source ~/virtualenv/python2.7/bin/activate
  - python -c "import cartopy.tests.mpl; print cartopy.tests.mpl.failed_images_html()"
